# Generated by Django 5.2.4 on 2025-08-03 17:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('webhook_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('virtual_number', models.CharField(help_text='The virtual number assigned to this client', max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('converted', 'Converted'), ('lost', 'Lost')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp from our server when the lead was created.')),
                ('call_timestamp', models.DateTimeField(blank=True, help_text='Editable timestamp from the webhook for the actual call time.', null=True)),
                ('call_duration', models.IntegerField(default=0, help_text='Duration of the call in seconds.')),
                ('recording_url', models.URLField(blank=True, max_length=512, null=True)),
                ('first_contacted_at', models.DateTimeField(blank=True, help_text="Timestamp when status was first changed to 'Contacted'.", null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='leads.client')),
            ],
        ),
    ]
